// <auto-generated />
using System;
using System.Globalization;
using System.Resources;

namespace BeltTensionTest.WPF.Properties
{
    /// <summary>
    ///   Strongly-typed resource class for localized strings.
    /// </summary>
    public static class Resources
    {
        private static ResourceManager? resourceMan;

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        public static ResourceManager ResourceManager
        {
            get
            {
                if (resourceMan == null)
                {
                    resourceMan = new ResourceManager("BeltTensionTest.WPF.Properties.Resources", typeof(Resources).Assembly);
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Culture override for resource lookups.
        /// </summary>
        public static CultureInfo? Culture { get; set; }

        public static string CloseToolTip => ResourceManager.GetString("CloseToolTip", Culture ?? CultureInfo.CurrentUICulture) ?? string.Empty;
        public static string BuyButtonToolTip => ResourceManager.GetString("BuyButtonToolTip", Culture ?? CultureInfo.CurrentUICulture) ?? string.Empty;
        public static string LaterButtonToolTip => ResourceManager.GetString("LaterButtonToolTip", Culture ?? CultureInfo.CurrentUICulture) ?? string.Empty;
        public static string SupportProjectTitle => ResourceManager.GetString("SupportProjectTitle", Culture ?? CultureInfo.CurrentUICulture) ?? string.Empty;
        public static string WindowTitle => ResourceManager.GetString("WindowTitle", Culture ?? CultureInfo.CurrentUICulture) ?? string.Empty;
        public static string Curve => ResourceManager.GetString("Curve", Culture ?? CultureInfo.CurrentUICulture) ?? string.Empty;
    }
}
